### PR TITLE
fix(push): truncate impact too many tables

### LINKED ISSUE #79: [BUG] Push truncate impact too many tables
# Problem

Ingress Descriptor defines a cluster of two table (country->city).
All other relations are disabled.

When using command `lino push truncate` this happens:

```
{"action":"truncate","table":"payment_p2007_01"}
{"action":"truncate","table":"payment_p2007_04"}
{"action":"truncate","table":"payment_p2007_06"}
{"action":"truncate","table":"rental"}
{"action":"truncate","table":"payment_p2007_03"}
{"action":"truncate","table":"payment_p2007_02"}
{"action":"truncate","table":"payment_p2007_05"}
{"action":"truncate","table":"payment"}
{"action":"truncate","table":"store"}
{"action":"truncate","table":"staff"}
{"action":"truncate","table":"customer"}
{"action":"truncate","table":"address"}
{"action":"truncate","table":"inventory"}
{"action":"truncate","table":"film_actor"}
{"action":"truncate","table":"city"}
{"action":"truncate","table":"film"}
{"action":"truncate","table":"film_category"}
{"action":"truncate","table":"category"}
{"action":"truncate","table":"language"}
{"action":"truncate","table":"actor"}
{"action":"truncate","table":"country"}
```

All of the tables mentionned in the ingress decriptor are impacted.

# Solution

Change the following method, so it returns only tables that are parts of a active relation (lookup: true).

https://github.com/CGI-FR/LINO/blob/14d10063d3eaddfe62a5f6031d0d20020f2c38f9/pkg/push/model_plan.go#L45-L82

### PR DESCRIPTION
**Pull request by adrienaury**
close #79

### CODE REVIEW

File: internal/app/push/cli.go [hunk 1]
```diff
@@ -273,7 +273,9 @@ func (c idToPushConverter) getPlan(id id.IngressDescriptor) push.Plan {
 
 	for idx := uint(0); idx < id.Relations().Len(); idx++ {
 		rel := id.Relations().Relation(idx)
-		relations = append(relations, c.getRelation(rel.Name()))
+		if rel.LookUpChild() || rel.LookUpParent() {
```
Comment (youen) [inline internal/app/push/cli.go:276]: We should check the full path from the start table.

For example if one relation is deactivated (BC) all relations after should be deactivated (CD).

```
A --> B -\-> C --> D
```

**Review by youen — APPROVED** [review]
